CREATE OR REPLACE ICEBERG TABLE EV_ANALYTICS.GOLD.ICE_AGG_EV_TYPE_SHARE_BY_COUNTY
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = 'EV_ICEBERG_VOL'
  BASE_LOCATION = 'agg_ev_type_share_by_county/'
AS
  SELECT * FROM EV_ANALYTICS.GOLD.AGG_EV_TYPE_SHARE_BY_COUNTY