CREATE OR REPLACE ICEBERG TABLE EV_ANALYTICS.GOLD.ICE_AGG_ADOPTION_BY_COUNTY
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = 'EV_ICEBERG_VOL'
  BASE_LOCATION = 'agg_adoption_by_county/'
AS
  SELECT * FROM EV_ANALYTICS.GOLD.AGG_ADOPTION_BY_COUNTY