CREATE OR REPLACE ICEBERG TABLE EV_ANALYTICS.GOLD.ICE_AGG_REGISTRATIONS_BY_YEAR_MAKE
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = 'EV_ICEBERG_VOL'
  BASE_LOCATION = 'agg_registrations_by_year_make/'
AS
  SELECT * FROM EV_ANALYTICS.GOLD.AGG_REGISTRATIONS_BY_YEAR_MAKE