CREATE OR REPLACE SHARE EV_GOLD_SHARE
  COMMENT = 'WA EV registration Gold-layer aggregates for partner analytics';

GRANT USAGE ON DATABASE EV_ANALYTICS TO SHARE EV_GOLD_SHARE;
GRANT USAGE ON SCHEMA EV_ANALYTICS.GOLD TO SHARE EV_GOLD_SHARE;

GRANT SELECT ON VIEW EV_ANALYTICS.GOLD.SV_AGG_REGISTRATIONS_BY_YEAR_MAKE TO SHARE EV_GOLD_SHARE;
GRANT SELECT ON VIEW EV_ANALYTICS.GOLD.SV_AGG_ADOPTION_BY_COUNTY TO SHARE EV_GOLD_SHARE;
GRANT SELECT ON VIEW EV_ANALYTICS.GOLD.SV_AGG_EV_TYPE_SHARE_BY_COUNTY TO SHARE EV_GOLD_SHARE