CREATE OR REPLACE SECURE VIEW EV_ANALYTICS.GOLD.SV_AGG_REGISTRATIONS_BY_YEAR_MAKE AS
SELECT * FROM EV_ANALYTICS.GOLD.AGG_REGISTRATIONS_BY_YEAR_MAKE;

CREATE OR REPLACE SECURE VIEW EV_ANALYTICS.GOLD.SV_AGG_ADOPTION_BY_COUNTY AS
SELECT * FROM EV_ANALYTICS.GOLD.AGG_ADOPTION_BY_COUNTY;

CREATE OR REPLACE SECURE VIEW EV_ANALYTICS.GOLD.SV_AGG_EV_TYPE_SHARE_BY_COUNTY AS
SELECT * FROM EV_ANALYTICS.GOLD.AGG_EV_TYPE_SHARE_BY_COUNTY