create or replace TABLE EV_ANALYTICS.BRONZE.EV_RAW (
	RAW_RECORD VARIANT,
	FILE_NAME VARCHAR(16777216),
	FILE_ROW_NUMBER NUMBER(38,0),
	INGESTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	BATCH_ID VARCHAR(16777216)
);