-- 1. Set the schedule on the dynamic table
ALTER DYNAMIC TABLE EV_ANALYTICS.SILVER.EV_REGISTRATIONS
  SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

-- 2. Attach NULL_COUNT on key columns
ALTER DYNAMIC TABLE EV_ANALYTICS.SILVER.EV_REGISTRATIONS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (dol_vehicle_id);

ALTER DYNAMIC TABLE EV_ANALYTICS.SILVER.EV_REGISTRATIONS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (make);

ALTER DYNAMIC TABLE EV_ANALYTICS.SILVER.EV_REGISTRATIONS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (county);

-- 3. Attach DUPLICATE_COUNT on the primary key
ALTER DYNAMIC TABLE EV_ANALYTICS.SILVER.EV_REGISTRATIONS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (dol_vehicle_id);

-- 4. Attach ROW_COUNT (table-level, uses a dummy column ref)
ALTER DYNAMIC TABLE EV_ANALYTICS.SILVER.EV_REGISTRATIONS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (dol_vehicle_id);