-- Schedule on Silver
ALTER DYNAMIC TABLE EV_ANALYTICS.SILVER.EV_REGISTRATIONS
  SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

-- Attach custom DMFs to Silver
ALTER DYNAMIC TABLE EV_ANALYTICS.SILVER.EV_REGISTRATIONS
  ADD DATA METRIC FUNCTION
    EV_ANALYTICS.GOVERNANCE.INVALID_RANGE_COUNT ON (range_is_researched, electric_range);

ALTER DYNAMIC TABLE EV_ANALYTICS.SILVER.EV_REGISTRATIONS
  ADD DATA METRIC FUNCTION
    EV_ANALYTICS.GOVERNANCE.INVALID_MODEL_YEAR_COUNT ON (model_year);

-- Schedule on Fact
ALTER DYNAMIC TABLE EV_ANALYTICS.GOLD.FACT_EV_REGISTRATION
  SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

-- Attach orphan check to Fact
ALTER DYNAMIC TABLE EV_ANALYTICS.GOLD.FACT_EV_REGISTRATION
  ADD DATA METRIC FUNCTION
    EV_ANALYTICS.GOVERNANCE.ORPHAN_FACT_COUNT ON (vehicle_key);