create or replace TABLE EV_ANALYTICS.GOVERNANCE.PIPELINE_AUDIT (
	AUDIT_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	BATCH_ID VARCHAR(16777216) NOT NULL,
	RUN_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	BRONZE_ROW_COUNT NUMBER(38,0),
	SILVER_ROW_COUNT NUMBER(38,0),
	QUARANTINE_COUNT NUMBER(38,0),
	GOLD_FACT_COUNT NUMBER(38,0),
	BRONZE_MINUS_DUPES NUMBER(38,0),
	RECONCILE_BRONZE_SILVER BOOLEAN,
	RECONCILE_SILVER_FACT BOOLEAN,
	OVERALL_STATUS VARCHAR(16777216),
	NOTES VARCHAR(16777216)
);