create or replace task EV_ANALYTICS.GOVERNANCE.TASK_DQ
	warehouse=WH_EV_DEMO
	after EV_ANALYTICS.GOVERNANCE.TASK_TRIGGER_REFRESH
	as CALL EV_ANALYTICS.GOVERNANCE.SP_RECONCILE('batch_' || TO_CHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS'));