create or replace task EV_ANALYTICS.GOVERNANCE.TASK_TRIGGER_REFRESH
	warehouse=WH_EV_DEMO
	after EV_ANALYTICS.GOVERNANCE.TASK_INGEST
	as ALTER DYNAMIC TABLE EV_ANALYTICS.SILVER.EV_REGISTRATIONS REFRESH;